server:
  port: 9000
spring:
  application:
    name: image-service

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}


object-storage:
  provider: tencent
  settings:
    accessKey: AKIDzxpaEjnVgNw3ymHuRqPwr54LUR12AKdT
    secretKey: nJtJbxmqfWAIg6rrSBdmFjIF9namBhts
    bucketName: wmpicture-1256286187
    region: ap-shanghai
    anonymousBucketName: prod-dae-static