server:
  port: 8888
spring:
  application:
    name: waimung-eureka
eureka:
  client:
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka
    dollar-replacement: false
  server:
    enable-self-preservation: false # 关闭自我保护模式（缺省为打开）
    eviction-interval-timer-in-ms: 5000 #续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）